### ISSUE TITLE
GitHub Actions is deprecating 'node16' actions

### ISSUE THREAD

**Issue by glx22** [ammaraskar/msvc-problem-matcher#3]
Since GitHub Actions is deprecating 'node16' actions, this now pops up warning annotations when it runs in a workflow.

See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by ammaraskar** [comment]
Released an update here, thanks! https://github.com/ammaraskar/msvc-problem-matcher/releases/tag/0.3.0
